"""transaction match status and payment events

Revision ID: 33f253b307f4
Revises: 0abe0a1fcdc1
Create Date: 2026-07-18 18:13:12.563902

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33f253b307f4'
down_revision: str | Sequence[str] | None = '0abe0a1fcdc1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name=op.f('fk_payment_events_registration_id_registrations')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_payment_events_tournament_id_tournaments')),
    sa.ForeignKeyConstraint(['transaction_id'], ['bank_transactions.id'], name=op.f('fk_payment_events_transaction_id_bank_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events'))
    )
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status_reason', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('matched_registration_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bank_transactions_matched_registration_id_registrations'), 'registrations', ['matched_registration_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bank_transactions_matched_registration_id_registrations'), type_='foreignkey')
        batch_op.drop_column('matched_registration_id')
        batch_op.drop_column('status_reason')
        batch_op.drop_column('status')

    op.drop_table('payment_events')
    # ### end Alembic commands ###
