"""Split discipline identity: code -> slug, plus weapon/gender/material.

`disciplines.code` was identity, classification, and HR join key at once
(design discipline-identity). This splits it: `slug` becomes the stored
identity (values unchanged, so every existing URL, export, and stored sheet
column keeps resolving), and `weapon`/`gender`/`material` become stored
classification, backfilled by parsing the old code — total coverage, since
every existing code was generated by `taxonomy._build()` from exactly those
three facets. `UNIQUE(tournament_id, code)` becomes `UNIQUE(tournament_id,
slug)`; the constraint survives verbatim, only its meaning narrows.

No data migration for `tournaments.hr_category_map` or
`hr_snapshot_ratings.discipline_code`: their keys are taxonomy codes today
and stay taxonomy codes.

Revision ID: 52ba5b743d48
Revises: a3f7c9d21e08
Create Date: 2026-08-02
"""

import sqlalchemy as sa
from sqlalchemy import column, table

from alembic import op

revision = "52ba5b743d48"
down_revision = "a3f7c9d21e08"
branch_labels = None
depends_on = None


def _parse_code(code: str) -> tuple[str, str, str]:
    """Inlined copy of app.taxonomy.parse_code — migrations must not depend on
    application code that may change shape after this revision is written."""
    material = "Plastic" if code.startswith("Plastic ") else ""
    rest = code.removeprefix("Plastic ").strip()
    gender = ""
    if rest and rest[-1] in ("W", "M"):
        gender = rest[-1]
        rest = rest[:-1]
    return rest, gender, material


def upgrade() -> None:
    with op.batch_alter_table("disciplines") as batch:
        batch.add_column(sa.Column("weapon", sa.String(length=30), nullable=True))
        batch.add_column(sa.Column("gender", sa.String(length=1), nullable=True))
        batch.add_column(sa.Column("material", sa.String(length=10), nullable=True))

    conn = op.get_bind()
    disciplines = table(
        "disciplines",
        column("id", sa.Integer),
        column("code", sa.String),
        column("weapon", sa.String),
        column("gender", sa.String),
        column("material", sa.String),
    )
    rows = conn.execute(sa.select(disciplines.c.id, disciplines.c.code)).fetchall()
    for row in rows:
        weapon, gender, material = _parse_code(row.code)
        conn.execute(
            disciplines.update()
            .where(disciplines.c.id == row.id)
            .values(weapon=weapon, gender=gender, material=material)
        )

    # a plain column rename, with no explicit constraint surgery: SQLite
    # batch mode recreates the table from the reflected original, so the
    # existing UNIQUE(tournament_id, code) constraint's column reference
    # follows the rename automatically and becomes UNIQUE(tournament_id,
    # slug) — same constraint, same name, narrower meaning
    with op.batch_alter_table("disciplines") as batch:
        batch.alter_column("weapon", existing_type=sa.String(length=30), nullable=False)
        batch.alter_column("gender", existing_type=sa.String(length=1), nullable=False)
        batch.alter_column("material", existing_type=sa.String(length=10), nullable=False)
        batch.alter_column(
            "code",
            new_column_name="slug",
            existing_type=sa.String(length=10),
            type_=sa.String(length=30),
        )


def downgrade() -> None:
    conn = op.get_bind()
    disciplines = table(
        "disciplines",
        column("id", sa.Integer),
        column("tournament_id", sa.Integer),
        column("slug", sa.String),
        column("weapon", sa.String),
        column("gender", sa.String),
        column("material", sa.String),
    )
    rows = conn.execute(
        sa.select(
            disciplines.c.tournament_id,
            disciplines.c.weapon,
            disciplines.c.gender,
            disciplines.c.material,
        )
    ).fetchall()
    seen: set[tuple[int, str]] = set()
    for row in rows:
        material_prefix = "" if row.material in ("", "Steel") else row.material
        gender_suffix = row.gender if row.gender in ("W", "M") else ""
        code = f"{material_prefix} {row.weapon}{gender_suffix}".strip()
        key = (row.tournament_id, code)
        if key in seen:
            raise RuntimeError(
                f"downgrade blocked: tournament {row.tournament_id} holds two "
                f"disciplines of taxonomy code {code!r}, which has no "
                "representation in the pre-split schema"
            )
        seen.add(key)

    with op.batch_alter_table("disciplines") as batch:
        batch.alter_column(
            "slug",
            new_column_name="code",
            existing_type=sa.String(length=30),
            type_=sa.String(length=10),
        )
        batch.drop_column("material")
        batch.drop_column("gender")
        batch.drop_column("weapon")
