"""hr fighters index and rating snapshots

Revision ID: b0a1f1e36817
Revises: 0cf30c31e7a2
Create Date: 2026-07-18 23:42:58.275324

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b0a1f1e36817'
down_revision: str | Sequence[str] | None = '0cf30c31e7a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_fighters',
    sa.Column('hr_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_folded', sa.String(length=200), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('club', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('hr_id', name=op.f('pk_hr_fighters'))
    )
    with op.batch_alter_table('hr_fighters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hr_fighters_name_folded'), ['name_folded'], unique=False)

    op.create_table('hr_index_refreshes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('fighter_count', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hr_index_refreshes'))
    )
    op.create_table('hr_rating_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fencer_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_hr_rating_snapshots_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hr_rating_snapshots'))
    )
    op.create_table('hr_snapshot_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('hr_id', sa.Integer(), nullable=False),
    sa.Column('discipline_code', sa.String(length=15), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['hr_rating_snapshots.id'], name=op.f('fk_hr_snapshot_ratings_snapshot_id_hr_rating_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hr_snapshot_ratings')),
    sa.UniqueConstraint('snapshot_id', 'hr_id', 'discipline_code', name=op.f('uq_hr_snapshot_ratings_snapshot_id'))
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('hr_category_map', sa.JSON(), nullable=False, server_default='{}')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('hr_category_map')

    op.drop_table('hr_snapshot_ratings')
    op.drop_table('hr_rating_snapshots')
    op.drop_table('hr_index_refreshes')
    with op.batch_alter_table('hr_fighters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hr_fighters_name_folded'))

    op.drop_table('hr_fighters')
    # ### end Alembic commands ###
