"""core multi-tenant data model

Revision ID: bd837ac38846
Revises: 666ccfb15cd3
Create Date: 2026-07-17 23:12:27.241603

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd837ac38846'
down_revision: str | Sequence[str] | None = '666ccfb15cd3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('hr_id', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('club', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hr_id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('reservation_validity_days', sa.Integer(), nullable=False),
    sa.Column('reminder_day', sa.Integer(), nullable=False),
    sa.Column('amount_tolerance_percent', sa.Integer(), nullable=False),
    sa.Column('refundable_until', sa.Date(), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('unpaid_list_treatment', sa.Enum('hidden', 'greyed', name='unpaidlisttreatment', native_enum=False, length=30), nullable=False),
    sa.Column('early_bird_until', sa.Date(), nullable=True),
    sa.Column('weapon_rental_fee', sa.Integer(), nullable=False),
    sa.Column('weapon_rental_fee_early', sa.Integer(), nullable=True),
    sa.Column('afterparty_fee', sa.Integer(), nullable=False),
    sa.Column('afterparty_fee_early', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Integer(), nullable=False),
    sa.Column('fee_early', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'code')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('fencer_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('state', sa.Enum('reserved', 'paid', 'expired', 'cancelled', name='registrationstate', native_enum=False, length=30), nullable=False),
    sa.Column('vs', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refundable', sa.Boolean(), nullable=True),
    sa.Column('refund_state', sa.Enum('not_applicable', 'pending', 'refunded', name='refundstate', native_enum=False, length=30), nullable=False),
    sa.Column('weapon_rentals', sa.JSON(), nullable=False),
    sa.Column('afterparty', sa.Boolean(), nullable=False),
    sa.Column('aftersparring', sa.Boolean(), nullable=False),
    sa.Column('accommodation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fencer_id'], ['fencers.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'fencer_id'),
    sa.UniqueConstraint('vs')
    )
    op.create_table('tournament_organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('fencer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fencer_id'], ['fencers.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'fencer_id')
    )
    op.create_table('registration_disciplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('is_substitute', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'discipline_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_disciplines')
    op.drop_table('tournament_organizers')
    op.drop_table('registrations')
    op.drop_table('disciplines')
    op.drop_table('tournaments')
    op.drop_table('fencers')
    # ### end Alembic commands ###
