"""fencer password_hash

Revision ID: c92e8a53fc72
Revises: bd837ac38846
Create Date: 2026-07-17 23:33:32.002673

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c92e8a53fc72'
down_revision: str | Sequence[str] | None = 'bd837ac38846'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fencers', sa.Column('password_hash', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fencers', 'password_hash')
    # ### end Alembic commands ###
