"""import batches, rows, decisions

Revision ID: d37c5eced46f
Revises: 0646565991a0
Create Date: 2026-07-18 20:47:27.480531

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd37c5eced46f'
down_revision: str | Sequence[str] | None = '0646565991a0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_import_batches_tournament_id_tournaments')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['fencers.id'], name=op.f('fk_import_batches_uploaded_by_fencers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_table('import_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_import_decisions_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_decisions')),
    sa.UniqueConstraint('tournament_id', 'kind', 'key', name=op.f('uq_import_decisions_tournament_id'))
    )
    op.create_table('imported_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_imported_rows_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_imported_rows_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imported_rows')),
    sa.UniqueConstraint('batch_id', 'key', name=op.f('uq_imported_rows_batch_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imported_rows')
    op.drop_table('import_decisions')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
