"""fencer language

Revision ID: f6495f6a87e8
Revises: e58f2c7d91a4
Create Date: 2026-07-19 22:02:22.650173

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6495f6a87e8'
down_revision: str | Sequence[str] | None = 'e58f2c7d91a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fencers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'language', sa.String(length=10), nullable=False, server_default='cs'
            )
        )

    with op.batch_alter_table('fencers', schema=None) as batch_op:
        batch_op.alter_column('language', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fencers', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
